name: CI
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Rubocop checks
      uses: gimenete/rubocop-action@1.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
