name: CI
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Rubocop checks
    - uses: actions/checkout@v2
    - uses: fregante/setup-git-user@v1
    - uses: gimenete/rubocop-action@1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
