name: CI
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Rubocop checks
      uses: gimenete/rubocop-action@1.0
    - uses: fregante/setup-git-user@v1 
