name: CI
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Github Rubocop Action
      uses: luizfonseca/github-actions-rubocop@1.5.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
